ENCODING=$1
MAP=$2
ROBOTS=$3
DISTANCES=$4

./ext_map_time.sh $ENCODING $MAP $ROBOTS $DISTANCES
./ext_map_variables.sh $ENCODING $MAP $ROBOTS $DISTANCES
./ext_map_sats.sh $ENCODING $MAP $ROBOTS $DISTANCES
#./ext_map_CNF.sh $ENCODING $MAP $ROBOTS $DISTANCES